USE form_recipes;

CREATE TABLE USUARIOS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_USER VARCHAR(50) NOT NULL,
  GENERO VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  SENHA VARCHAR(15) NOT NULL
);

SELECT * FROM USUARIOS;